In [1]:
# polarity data에 새로운 데이터 셋을 추가하는 코드

import os
import data_helpers
import json
import pandas as pd

data = pd.read_csv("train.tsv",
                  header=0, delimiter='\t', quoting=3, encoding='CP949')

#data.columns = ['sentence', 'label']
#print(data.shape)


#data3.head(10)
#print(data3.shape)
data.head(10)
#data.tail(10)

#with open('Dataset for Detection of Cyber-Trolls.json') as json_file:
#    json_data = json.load(json_file)
    
#with open('Data9set for Detection of Cyber-Trolls.json') as f:
#    data = [json.loads(line) for line in f]
    
#f= open("rt-polaritydata/rt-polarity-Copy1.neg","+a")
#count = 0

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2
5,6,1,of escapades demonstrating the adage that what...,2
6,7,1,of,2
7,8,1,escapades demonstrating the adage that what is...,2
8,9,1,escapades,2
9,10,1,demonstrating the adage that what is good for ...,2

In [2]:
from multiprocessing import Pool

In [6]:
#for root, dirs, files in os.walk('rt-polaritydata/test.neg')
#    for fname in files:
        
file_name = 'rt-polaritydata/test2.pos'
f2=open(file_name, "+a")
        
#Open the file back and read the contents

for i in range (0, 156060):
    if data["Sentiment"][i] >= 3:
        f2.write(data['Phrase'][i]+"\n")
                        
f2.close()

In [4]:
 # 참고 : https://gist.github.com/yong27/7869662
    # http://www.racketracer.com/2016/07/06/pandas-in-parallel/
    # 속도 개선을 위해 멀티 스레드로 작업하도록
    @staticmethod
    def _apply_df(args):
        df, func, kwargs = args
        return df.apply(func, **kwargs)

    @staticmethod
    def apply_by_multiprocessing(df, func, **kwargs):
        # 키워드 항목 중 workers 파라메터를 꺼냄
        workers = kwargs.pop('workers')
        # 위에서 가져온 workers 수로 프로세스 풀을 정의
        pool = Pool(processes=workers)
        # 실행할 함수와 데이터프레임을 워커의 수 만큼 나눠 작업
        result = pool.map(KaggleWord2VecUtility._apply_df, [(d, func, kwargs)
                for d in np.array_split(df, workers)])
        pool.close()
        # 작업 결과를 합쳐서 반환
        return pd.concat(result)

IndentationError: unexpected indent (<ipython-input-4-0294414787f5>, line 4)